[build]
  command = "npm run build"
  publish = "out"
  ignore = "false"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"

# Disable all plugins
[plugins]
  # No plugins
